[project]
name = "OKXsignal"
version = "0.1"
description = "Advanced crypto signal computation"
authors = [{name = "Robert"}]
dependencies = []
requires-python = ">=3.9"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
